version: "2"
linters:
  default: none
  enable:
    - dupl
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - testifylint
    - modernize
    - nestif
    - wrapcheck
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - wrapperFunc
        - hugeParam
        - rangeValCopy
        - singleCaseSwitch
        - ifElseChain
      enabled-tags:
        - performance
        - style
        - experimental
    govet:
      enable:
        - shadow
    lll:
      line-length: 140
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - gosec
        path: _test\.go
      - linters:
          - revive
          - unparam
          - unused
        path: _test\.go$
        text: unused-parameter
